# Generated by Django 4.1.6 on 2023-02-11 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_meal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
