# Generated by Django 4.1.6 on 2023-02-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_meal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='slug',
        ),
    ]
